### PR TITLE
make newly created event appear on /ManageEvents page right away

### PR DESCRIPTION
**Pull request by bcuz**
fix is in first commit. second commit is just refactoring the DELETE_EVENT_SUCCESS action

@mjenkins9605 this should be pretty straighforward to review. the fix is essentially copying what Louis did for the `deleteEvent` in `eventActions.js ` to grab all the events

### CODE REVIEW

**Comment by bcuz** [comment]
[bug fix: events array should contain newly created event](https://trello.com/c/V5JMj9ye/120-bug-fix-events-array-should-contain-newly-created-event)

**Comment by wmemorgan** [comment]
@bcuz - Does this PR address the bug you mentioned in your last PR https://github.com/social-tours/front-end/pull/66?

**Comment by bcuz** [comment]
@wmemorgan yes

**Comment by bcuz** [comment]
[bug fix: events redux state should contain newly created event](https://trello.com/c/V5JMj9ye/120-bug-fix-events-redux-state-should-contain-newly-created-event)

**Pull request merged**
